name: Rust
on: [push, pull_request]
permissions:
  contents: read
concurrency:
  group: rust-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - run: rustup toolchain install 1.90.0 --profile minimal --component rustfmt --component clippy
      - run: cargo +1.90.0 fmt --check
      - run: cargo +1.90.0 clippy --locked --all-targets -- -D warnings
      - run: cargo +1.90.0 test --locked --no-fail-fast
